### ISSUE TITLE
[G3. Dev process] Onboarding check list for ODAHU QA engineer

### ISSUE THREAD

**Issue by alinaignatiuk** [odahu/odahu#36]
Create an onboarding check-list for the ODAHU QA engineer where all services/tools, documents and environments that are relevant for ODAHU testing are specified

**Comment by alinaignatiuk** [comment]
Please place it here: https://kb.epam.com/display/EPMCBDCC/%5BODAHU%5D+Onboarding+process

**Comment by BPylypenko** [comment]
@alinaignatiuk @viravit 
I have updated the page: [[ODAHU] Onboarding process](https://kb.epam.com/x/7frsWg).
Please take a look and leave comments or suggest improvements.
